name: Fortify Scan (Test Only)

on:
  workflow_dispatch:

jobs:
  fortify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build project (ignore failures)
        run: mvn clean install -DskipTests || true

      - name: Run Fortify Scan
        uses: fortify/github-action@v3
        env:
          SSC_URL: "https://3.214.170.252:8443/ssc"
          SC_CONTROLLER_URL: "https://3.214.170.252:10443/scancentral-ctrl"
          SSC_TOKEN: d3247deb-c180-462f-a02d-08138ea611d9
          SC_SAST_TOKEN: CHANGEME123!
          SSC_APPVERSION: "A-git:1.0"
          FCLI_DEBUG: true
